spring: 
 sql:
  init:
   mode: always

  application:
    name: warehouse-sensor-measurement-system

  r2dbc:
    url: r2dbc:h2:mem:///warehousedb
    username: sa
    password:

server:
  port: 8081

logging:
  level:
    root: INFO